Updated Zendesk theme for OCW
mitodl/ocw-zendesk-theme pull request #2
Opened 2021-12-29 11:07 UTC by Wassaf-Shahzad

## Checklist
[x] Match the designs to the [InVision mock up](https://projects.invisionapp.com/share/3Z123TYWM64W#/screens/459218314_Zendesk_-_Help_-_FAQs)
- [x] `Submit a request` link (upper right) will open a page to submit a new support request ([xPRO example](https://xpro.zendesk.com/hc/en-us/requests/new))
- [x] The number of buttons (that currently read: `Label of button`) and their text are not yet determined. Ensure the color and font are correct.
- [x] Use fonts (and colors, if necessary) that match the OCW site.
- [x] The title of page should be `Support Center` rather than `Help & FAQs`
- [x] Add a `Can't find what you're looking for?` section, similar to xPRO. Just above the footer. 
   - [x] The horizontal rule should use the red color from the search button
   - [x] The contact use button should use the red color form the search button and have white text
   - [x] The section background-color should be white
   - [x] Clicking `Contact Us` will open a page to submit a new support request ([xPRO example](https://xpro.zendesk.com/hc/en-us/requests/new)) 
![image](https://user-images.githubusercontent.com/21342568/147391544-04d3e111-06a4-4431-9b7f-2f8585ae4b81.png)
- [ ] The footer should match the OCW site footer

## Live Preview
Live preview for the design can be viewed on
- https://test4772.zendesk.com/hc/en-us

##  Blockers:
I am currently blocked by the following issues
- Need a design for the footer (Screenshot will do to) 
- Need hero image

## Screenshots

![Screenshot 2021-12-29 at 3 37 58 PM](https://user-images.githubusercontent.com/87968618/147655365-ba193475-0eaa-4f71-8324-22dc4b5fdddd.png)
<img width="1122" alt="Screenshot 2021-12-29 at 3 38 17 PM" src="https://user-images.githubusercontent.com/87968618/147655576-96476104-8fe0-4970-8509-d6f0909e2074.png">
<img width="701" alt="Screenshot 2021-12-29 at 3 38 32 PM" src="https://user-images.githubusercontent.com/87968618/147655636-2c31b59c-1842-4626-b332-f5cab9940a19.png">
<img width="1432" alt="Screenshot 2021-12-29 at 4 02 16 PM" src="https://user-images.githubusercontent.com/87968618/147655702-2364141c-999e-4cdd-99be-2cd31595159b.png">

2021-12-29 18:53 UTC, briangrossman commented
@Wassaf-Shahzad 
This is looking good so far. I put [some notes](https://github.com/mitodl/ocw-zendesk-theme/issues/1#issuecomment-1002731611) on the footer in the issue and we're waiting on access to the hero image.

2022-01-03 11:54 UTC, Wassaf-Shahzad commented
> @Wassaf-Shahzad This is looking good so far. I put [some notes](https://github.com/mitodl/ocw-zendesk-theme/issues/1#issuecomment-1002731611) on the footer in the issue and we're waiting on access to the hero image.

@briangrossman 
As requested I have updated the footer and links.
You can view a deployed instance here
- https://test4772.zendesk.com/hc/en-us

2022-01-06 09:49 UTC, arslanashraf7 requested changes
I have added a few comments.

Along with those comments, there are a few things in general that can be fixed:
1) We still have MITxOnline references in the code, even the logo image in the header points to MITxOnline website's link. [ref](https://github.com/mitodl/ocw-zendesk-theme/blob/main/manifest.json#L167) - (I believe this is not the intended behavior @briangrossman ?)
2) The search bar width gets inconsistent when you see them on mobile (Screenshot attached below)
3) Although there is no copyright section in invision i think there should be one? (@briangrossman What do you think?)

Search Screenshot:
<img width="499" alt="Screenshot 2022-01-06 at 2 24 33 PM" src="https://user-images.githubusercontent.com/34372316/148362775-c10b18eb-77ec-4783-8854-af29ad2ee857.png">

2022-01-06 09:49 UTC, arslanashraf7 commented on styles/_footer.scss
> +    font-size: 15px;
This should be `14px` as per invision design. The company info on the left of the footer links is already 14.
```suggestion
    font-size: 14px;
```

2022-01-06 09:49 UTC, arslanashraf7 commented on styles/_footer.scss
> +    padding: 0 0 20px 0;
```suggestion
    padding: 0 0 20px;
```

2022-01-06 09:49 UTC, arslanashraf7 commented on styles/_footer.scss
> +        margin: 0 0 0 15px;
```suggestion
        margin-left: 15px;
```

2022-01-06 09:49 UTC, arslanashraf7 commented on templates/footer.hbs
> +        <li><a href="https://accessibility.mit.edu/">Accessibility</a></li>
There is a good probability that we might need to change these links at some points. So keeping them configurable through Zendesk admin settings instead of making changes on code would be a nice idea. So, all these links should be configurable.

How that's done? Have a look here https://github.com/mitodl/ocw-zendesk-theme/blob/main/manifest.json#L161

2022-01-06 09:49 UTC, arslanashraf7 commented on templates/footer.hbs
> +</script>
newline.

2022-01-06 09:49 UTC, arslanashraf7 commented on styles/_hero.scss
> +  background: #2a2929 url($ocw_background) repeat-x 50% 100%;
Don't think we need this background color. Only image would be fine
```suggestion
  background: url($ocw_background) repeat-x 50% 100%;
```

2022-01-06 17:13 UTC, pdpinch requested changes

2022-01-06 17:13 UTC, pdpinch commented on templates/header.hbs
> +      {{#link 'new_request' class='submit-a-request'}}Submit a request{{/link}}
FYI, in a future PR, we'll want to point this to an OCW-specific form instead of the ZenDesk form.

2022-01-06 23:02 UTC, briangrossman commented
> 1. We still have MITxOnline references in the code, even the logo image in the header points to MITxOnline website's link. [ref](https://github.com/mitodl/ocw-zendesk-theme/blob/main/manifest.json#L167) - (I believe this is not the intended behavior @briangrossman ?)

Correct. There shouldn't be any references to MITx Online in this repo. 


> 3. Although there is no copyright section in invision i think there should be one? (@briangrossman What do you think?)

Yes. I think that is probably a good idea. It should say: 
`© [Current Year] Massachusetts Institute of Technology`

Please make the layout similar to [MITx Online](https://mitxonline.mit.edu/) with the MIT logo and address in one row, and the copyright (left-aligned) and links (right-aligned) in a row beneath it (keep existing fonts and colors). Note that there's a chance this will need to be updated when we finalize the footer for the site itself. 

![image](https://user-images.githubusercontent.com/21342568/148464335-c74ef736-965d-4e68-bda2-15a973edefaf.png)

2022-01-07 09:51 UTC, Wassaf-Shahzad commented on manifest.json
> +      "identifier": "header_background_color",
Theming, colors and fonts should be defined in the manifest.json so that one theme can be adapted to multiple projects. This was my thought process and I believe some of these properties come predefined in the manifest.

2022-01-07 10:02 UTC, arslanashraf7 commented on manifest.json
> +      "identifier": "header_background_color",
That makes sense and I'm already okay with it 👍

2022-01-10 14:56 UTC, briangrossman commented
FYI: @Wassaf-Shahzad provided [this Zendesk site](https://test1437.zendesk.com/hc/en-us) for testing

2022-01-10 15:08 UTC, briangrossman commented
I reviewed the design of https://test1437.zendesk.com/hc/en-us and it looks good. 

One issue: the `Contact Us` link in the upper right still points to the old preview site. The `Contact Us` button on near the bottom of the page works fine though.

2022-01-12 08:47 UTC, arslanashraf7 requested changes
@Wassaf-Shahzad Thanks for incorporating the last feedback. I've added a few more comments. Feel free to ask questions if something i added isn't clear.

2022-01-12 08:47 UTC, arslanashraf7 commented on manifest.json
> +      "value": "https://test4772.zendesk.com/hc/en-us/requests/new"
This is the reason for what Brian mentioned in an [earlier comment](https://github.com/mitodl/ocw-zendesk-theme/pull/2#issuecomment-1008963434).

I think you did this change is light of [this suggestion](https://github.com/mitodl/ocw-zendesk-theme/pull/2#discussion_r779708735) and it totally makes sense to define the `Contact Us` link in the config variable as you did but there are two side effects that we should handle here:

1) We should add a check in the `*.hbs` files when there is no value defined for Contact Us link we should fallback to default ` {{#link 'new_request' class='submit-a-request'}}Contact Us{{/link}}`. This can be simple if condition.
2) We should use the same logic for all `Contact us` buttons so that we don't see the behavior mentioned in [this comment]([earlier comment](https://github.com/mitodl/ocw-zendesk-theme/pull/2#issuecomment-1008963434))

2022-01-12 08:47 UTC, arslanashraf7 commented on manifest.json
> +      "label": "ocw_label",
So, when we define a dict in the `manifest.json` to make something configurable there are a few other things that are related and need to be updated. 
1) The keys defined such as `ocw_description` and `ocw_label` should have a backing more human-readable text that would be shown in the theme settings configuration (See the screenshot below on how it looks).
2) In order to fix point#1, you'll need to add values in [en-us.json](https://github.com/mitodl/ocw-zendesk-theme/blob/main/translations/en-us.json) for `ocw_description` and `ocw_label` and any other keys you define. 
Note: These keys should be unique for each dict that's added in `manifest.json`

[This](https://github.com/mitodl/bootcamps-zendesk-theme/pull/5/files#diff-40a0db32d3684fe7f17838eafc7d3a216bdfd6b3c586270355010ea3239c5b3aR65) is a ref from Bootcamps PR

This is how it looks in the Zendesk them settings:
<img width="419" alt="Screenshot 2021-02-22 at 7 48 04 PM" src="https://user-images.githubusercontent.com/34372316/149091423-d0670749-d0da-444b-a362-64f649dc8151.png">

2022-01-12 08:47 UTC, arslanashraf7 commented on styles/_footer.scss
> +    // TODO: remove that line while adding hubspot form in the footer
Is it intentional? If yes, which line it is talking about?

2022-01-12 08:47 UTC, arslanashraf7 commented on templates/footer.hbs
> +        <li><a href="https://accessibility.mit.edu/">Accessibility</a></li>
@Wassaf-Shahzad I think this might have been overlooked, I think you did add the config values for the URLs but we are still using hardcoded URLs here? Or am I missing something?

2022-01-12 08:47 UTC, arslanashraf7 commented on styles/_header.scss
> +  padding-left: 2% !important;
I think this can be represented in single line
```suggestion
  padding: 20px 2% !important;
```
Currently, in the design, the `Contacts Us` link on the top right has a different border-spacing than the logo on the left. This will also make that consistent. You will need to remove the internal padding of `Contact Us` link which currently is 20px.
<img width="241" alt="Screenshot 2022-01-12 at 1 45 52 PM" src="https://user-images.githubusercontent.com/34372316/149093866-3113b519-fc88-4e72-a732-999184776637.png">

2022-01-12 13:41 UTC, Wassaf-Shahzad commented on styles/_footer.scss
> +    // TODO: remove that line while adding hubspot form in the footer
This is not my comment I will however remove it

2022-01-13 14:07 UTC, Wassaf-Shahzad commented
@pdpinch @arslanashraf7 
So i tried making the contact us page configurable however was unsuccessful as by making in configurable we lose the ability to verify whether the user has the privileges to even access that page. Zendesk verifies that itself and sets the 'new_request' identifier based on that.
Zendesks provides no helper to to check these `identifiers`

2022-01-13 14:14 UTC, arslanashraf7 approved these changes
Looks good 👍 

>So i tried making the contact us page configurable however was unsuccessful as by making in configurable we lose the ability to verify whether the user has the privileges to even access that page. Zendesk verifies that itself and sets the 'new_request' identifier based on that.
Zendesks provides no helper to to check these identifiers

Regarding this i think we can do that in some other PR when we go to a custom support form.

2022-01-14 11:29 UTC, Wassaf-Shahzad commented
> This is looking good, @Wassaf-Shahzad. Can you remove the horizontal repeat from the hero image and use something like `background-size:cover` so the image fills the space w/o repeating?![Screenshot 2022-01-14 at 4 19 38 PM]
> ![Screen Shot 2022-01-13 at 10 24 15 AM](https://user-images.githubusercontent.com/21342568/149359548-b338dab3-6faf-42c3-8cdf-febc4e3217d9.png)
> 
> ![Screen Shot 2022-01-13 at 10 26 58 AM](https://user-images.githubusercontent.com/21342568/149359576-a7f66b71-7735-4b25-acdb-3a1daf3e1148.png)

Done 
![Screenshot 2022-01-14 at 4 19 38 PM](https://user-images.githubusercontent.com/87968618/149507607-a8f9ced0-050f-49b5-a195-00e9400cf6e2.png)

2022-01-14 23:21 UTC, pdpinch approved these changes

2022-01-17 07:16 UTC, merged